# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    repo.promotions:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager",getRepository]
        arguments:
            - \BookShopBundle\Entity\Promotion
    promotion_manager:
        class: BookShopBundle\Service\PromotionManager
        arguments: ['@repo.promotions']
    price_calculator:
        class: BookShopBundle\Service\PriceCalculator
        arguments: ['@promotion_manager']
