# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    price_calculator:
        class: BookShopBundle\Service\PriceCalculator
        arguments: ['@doctrine.orm.entity_manager']
    #service_name:
    #    class: BookShopBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
